### ISSUE TITLE
backend structure refactoring

### ISSUE THREAD

**Issue by Kilerd** [zhang-accounting/zhang#126]
considering we are aiming to adopt the fully support of beancount, so zhang need to support multiple sources, like zhang itself, beancount, and others.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/3162379/226787170-2560c107-4387-453e-8f40-23ef273edcfe.png">

so we need to modify the frontend of backend. there would be some layer of it.
- layer **fs provider**: use to accept files from difference fs storage. mainly to resolve the issue of data synchronization. it means that zhang can access and modify the data in AWS S3, webdav and local fold as well directly without any synchronic machenism.
- layer **loader:** used to adopt different source. like beancount's user can enjoy zhang without any modifications.
- layer **core**: it's the key part of zhang, it provider it calculation logic and the database cache.
- layer **exporter**: use to export zhang's data to any target data, which are aslo very important. it provide a safenet for user to exit the zhang's ecosystem or use zhang's data to adopt into other financial systems.

**Comment by Harry-Chen** [comment]
Due to the fact that accounting tools share almost the same format (beancount, hledger, zhang), maybe a unified parser can be used to translate the text files to directives. Then a translation layer (namely loader in your design) can be used to process these directives, e.g. do nothing for `.zhang` format, merge `pad` and `balance` for `.bean` format, etc. In this way we can avoid many almost-identical code (such as grammar files and AST construction part).

**Comment by Kilerd** [comment]
regarding the fs provider layer, we have a separate ticket to trace: https://github.com/zhang-accounting/zhang/issues/105. 
we are still considering hot to adopt it. cuz when openDAL is opt-in, zhang will lose the control of file change event.
it may affect some user experience, said user user cannot receive the `reload` event from backend before user change the data(like create a new transaction, add a balance check for account).

**Comment by Kilerd** [comment]
in code structure, we plan to sepit monorepo into multiple via Cargo workspace:
- `ast`:  abstract statement tree of directives zhang supports
- `core`: how zhang handle `ast` to generate financial report, and store it into database
- `transformers/*`: what type of data source we support now, which `core` does not care aboout, need to handle parser and method convert to zhang's AST.
- `exporters/*`: given a export target, exporter need to handle how to convert from zhang's core data to target type.
- `server`: the builtin server
- `cli`: the entrypoint of cli program.
