### ISSUE TITLE
Arithmetic support for posting amounts

### ISSUE THREAD

**Issue by Kilerd** [zhang-accounting/zhang#253]
in beancount syntax, arithmetic symbols can be used in posting amount, it will be converted to a single amount when executing.
like
` Assets:BankCard 1*100 CNY` is equals to `Assets:BankCard 100 CNY`

I think zhang should support this feature.

and will be implemented in version 0.2

**Comment by Harry-Chen** [comment]
Done in #255.

**Comment by Kilerd** [comment]
need another PR to cherry-pick this feature to zhang parser

**Comment by Kilerd** [comment]
resolved in #259
