### ISSUE TITLE
Parse Error: pad

### ISSUE THREAD

**Issue by xiang578** [zhang-accounting/zhang#338]
开发者你好，在自己部署 docker 版本时遇到下面错误，不知道是什么原因

```
[2024-06-06T04:32:51Z INFO  zhang_server] version: 0.1.7, build date: 2024-03-28
[2024-06-06T04:32:51Z ERROR zhang] An error occur when serving zhang server: Parse Error 
    Path: accounts.bean   --> 140:12
        |
    140 | 2017-12-01 pad Assets:Cash:Wallet Equity:OpenBalance
        |            ^---
        |
        = expected tag, link, or quote_string
```

**Comment by Kilerd** [comment]
hi 你好，pad 指令并不被zhang支持 （在 playground中测试https://zhang-playground.zeabur.app/）。
<img width="755" alt="image" src="https://github.com/zhang-accounting/zhang/assets/3162379/4541ec7d-f92a-4905-809e-50c35d70e3d3">

考虑到你的报错信息中存在 `accounts.bean`，那么你在尝试加载 beancount文件。你是否已beancount兼容模式启动了呢？
参考这个网址 https://zhang-accounting.kilerd.me/installation/2-beancount_launch/

**Comment by xiang578** [comment]
量比较少，我先尝试手动改一下，感谢回复
