### ISSUE TITLE
尝试使用一个未定义的货币

### ISSUE THREAD

**Issue by xiang578** [zhang-accounting/zhang#339]
遇到挺多这个问题的，版本是 0.1.7，endpoint 是 main.bean。

报错对应的行

```
2021-06-01 price ETF_005827             3.1733 CNY
```

复制到 playground 没有报错

<img width="867" alt="image" src="https://github.com/zhang-accounting/zhang/assets/12624910/4092f519-d589-4120-b19c-14d4cc1e91c1">

**Comment by xiang578** [comment]
同样还有，当只定义 option "operating_currency" "CNY"
下面这行也会报错

```
1990-01-01 open Liabilities:CreditCards:BCM:MasterCard9380 CNY,USD
```

如果再定义 

`option "operating_currency" "USD"`

会报错 
账本中存在多项 operating currency 的配置，这是 zhang 中不推荐的用法

**Comment by Kilerd** [comment]
> 遇到挺多这个问题的，版本是 0.1.7，endpoint 是 main.bean。
> 
> 报错对应的行
> 
> ```
> 2021-06-01 price ETF_005827             3.1733 CNY
> ```
> 
> 复制到 playground 没有报错
> 
> <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/12624910/337252290-4092f519-d589-4120-b19c-14d4cc1e91c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzI2NTIsIm5iZiI6MTcxNzczMjM1MiwicGF0aCI6Ii8xMjYyNDkxMC8zMzcyNTIyOTAtNDA5MmY1MTktZDU4OS00MTIwLWIxOWMtMTRkNGNjMWU5MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAzNTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxM2MxODg1MmNiZGU2NDMwZWY2NDY1NzcwZjg1ZGZlMGE4MTI5NzhlYzRlZTMyNGJjM2ZhZWEyMzQ5OGJmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2EuJRYNTwnDjL299yIdpqIQANJ_KSxrqIVrE1B3DbfQ">

你好啊， 目前来说 playground 只用来检验语法是否正确，就你的截图来看，这是一个合法的语法。 但是币种没定义这是正常的报错现象

你需要用 commodity 来定义你个币种 
```
1970-01-01 commodity ETF_005827
```

**Comment by Kilerd** [comment]
> 同样还有，当只定义 option "operating_currency" "CNY" 下面这行也会报错
> 
> ```
> 1990-01-01 open Liabilities:CreditCards:BCM:MasterCard9380 CNY,USD
> ```
> 
> 如果再定义
> 
> `option "operating_currency" "USD"`
> 
> 会报错 账本中存在多项 operating currency 的配置，这是 zhang 中不推荐的用法

多个 operating_currency 的设置即便是在beancount中也是不推荐使用的写法，我这边建议你把CNY定义成 operating_currency， 然后用 commodity 语法来定义 USD


```
option "operating_currency" "CNY"

1970-01-01 commodity USD

1990-01-01 open Liabilities:CreditCards:BCM:MasterCard9380 CNY,USD
```

**Comment by xiang578** [comment]
感谢，已经解决问题
