### ISSUE TITLE
对beancount文件中的pad和balance 操作存在偶发性识别错误的问题

### ISSUE THREAD

**Issue by sea-ten** [zhang-accounting/zhang#386]
例如初始化账户的时候，通过Equity:Opening-Balances赋予了一个初始的值

![image](https://github.com/user-attachments/assets/6e13f6da-eeca-4715-9a0a-27c39b6dd1ad)

但是在流水记录中，Balance Check显示不通过，提示账号的累计是0.00 CNY

![image](https://github.com/user-attachments/assets/26671105-dbe8-4a4c-a27f-1190cb13556e)
![image](https://github.com/user-attachments/assets/fe4cbd99-c102-4989-aae1-c89108773b93)

但是大部分都能正常识别，显示类型为”Balance Pad“：

![image](https://github.com/user-attachments/assets/7317592a-2375-4ae6-9b96-fedf29026378)

现在有16条”账户定期对账不通过“的错误提示，看着挺难受的，不知道有没有解决方法

![image](https://github.com/user-attachments/assets/d1b9a51e-c394-437c-9cb5-038356a23f36)

**Comment by Kilerd** [comment]
hi，
你检查一下这个pad 是不是有对应多条balance？

**Comment by Kilerd** [comment]
这个balance 被识别成 balance check 就意味着找不到 pad 信息，那么它可能被其他balance 消耗掉了。

有可能写出一个最小复现吗？

**Comment by sea-ten** [comment]
> 这个balance 被识别成 balance check 就意味着找不到 pad 信息，那么它可能被其他balance 消耗掉了。
> 
> 有可能写出一个最小复现吗？

新开一个容器单独测了工商银行这个账户的初始化，是正常的。

然后我在原来的账本上，执行了相关操作
1. 查找这个工商银行账户的balance记录，发现除了初始化需要pad之外，还有很多balance记录是不需要用到pad，但我新增了一个“Equity:Balances:Test”账户并修改了初始化记录的pad和balance的时间后，这条记录就不报错了

2. 但我也发现了有另外一个银行账户，就只有一个pad和balance，一样是有报错的，也在修改了pad哈balance的时间后，恢复正常了。
![image](https://github.com/user-attachments/assets/2a20709d-46d6-4b69-aad3-e82dc9a93fcd)
![image](https://github.com/user-attachments/assets/07571d71-3cfb-4750-8464-944d60472be2)

3. 我打算继续修改其他报错记录的时间，或者将balance记录修改为普通的交易记录来进行初始化，来解决这个问题，另外在流水里面还发现大量Balance Check的记录。不过好在绝大部分的状态是pass的，不然就难受了。
![image](https://github.com/user-attachments/assets/6c2633c8-7ac0-4879-9780-91d95d208a5b)
