### ISSUE TITLE
Journals页面过滤功能的显示优化建议

### ISSUE THREAD

**Issue by sea-ten** [zhang-accounting/zhang#387]
![image](https://github.com/user-attachments/assets/bcbc27e5-4fbf-460c-afc9-ed83dca5597d)

![image](https://github.com/user-attachments/assets/f2979bc4-2b5f-4e40-8152-8fa8f1dcea2c)

**Comment by Kilerd** [comment]
这个在新的snapshot 版本已经修复了，还没有发正式版本，你可以尝试一下最新的版本 `docker pull kilerd/zhang:snapshot`

**Comment by Kilerd** [comment]
I gonna mark it as completed and close this issue, cuz we had fixed it in snapshot version and just wait for releasing new stable version.
